### ISSUE TITLE
경기과학고 텍 사용자협회 Slack 가입 안내

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/latex.gs.hs.kr#8]
한 줄 요약: **여기에 이메일 주소를 여기에 댓글로 알려주세요! https://gshstexsociety.slack.com 에 초대합니다.**

안녕하세요. 1대 회장 박승원입니다.
이미 졸업하였음에도, 염치 불구하고 마지막 한 가지 부탁만 드리려 합니다.
경기과학고를 떠난 뒤, 우리 협회를 보며 늘 아쉬웠던 점은, 협회 소속 재학생/교직원/졸업생 간 소통을 위한 창구가 없다는 점이었습니다. 그리하여, 뒤늦게나마 그를 위한 시설을 하나 개설하였기에 안내하고자 합니다.

소통을 위한 플랫폼으로는, 우리 협회와 유사한 공동체가 많이 사용하는 [Slack](https://slack.com/)이 좋아 보였습니다. 카카오톡과 같은 메신저만을 사용하시던 분들께서는 조금 생소할 수도 있습니다만, 카카오톡 등의 일반적인 메신저보다 더 편리한 점이 많습니다:
- 오랜 시간이 지나더라도, 주고받은 메시지 내용/문서/첨부파일을 쉽게 검색 가능
- 필요에 따라 얼마든지 channel(public/private)을 팀 안에서 채널 생성 가능 (예: 잡담 채널, 질문 채널, 33기 채널, 웹사이트 관리자 채널 등)
- GitHub에서 커밋했을 때 메시지를 날려주는 봇을 비롯한 여러 앱이 있음
- Code Snippet 기능을 통해 코드를 쉽게 리뷰 가능
- 웹 브라우저 / 데스크탑 설치버전 / 휴대폰 전체에서 손쉽게 접근 가능
- 등등... (플랫폼이 영어라는 점, 무료버전은 최대 10,000개의 메시지까지 볼 수 있다는 점이 거의 유일한 단점인 듯 합니다.)

이 플랫폼을 통해 우리 협회는 다음과 같은 것들을 할 수 있을 것으로 기대합니다:
- 전체/그룹 회원간 친목 도모
- 워크샵 진행 / 양식 제작 / 웹페이지 관리 등의 업무를 위한 회의
- qna 채널을 통한 질문/답변
- 등등...

그리하여, 우리 협회의 모든 회원 분들께 우리 협회의 슬랙 https://gshstexsociety.slack.com 에 들어오시길 적극 권합니다. 다만, 바로 들어오시지는 못하고, 이 슬랙 팀의 관리자가 직접 이메일로 초청해야 합니다. 그러니 **여기에 이메일 주소를 댓글로 알려주시면** 되겠습니다. 댓글을 달아 주시면, 저희 관리자(현재 1대 회장, 2대 회장 이렇게 2명입니다.) 중 한 명이 초대한 뒤, 초대되었다고 답글을 보내드리겠습니다.
많은 참여를 바랍니다.

PS. 이 이슈는 당분간 계속 열어두도록 하죠.

**Comment by seungwonpark** [comment]
@guitar79 : guitar79@naver.com

**Comment by seungwonpark** [comment]
@guitar79 초대해드렸습니다.

**Comment by SenikaRu** [comment]
99bannyzzz@gmail.com

**Comment by seungwonpark** [comment]
@SenikaRu 초대해드렸습니다.

**Comment by EC97B0EAB79C** [comment]
개인정보 문제가 있을 수 있으니 초대가 된 분들 이메일은 지워주세요

**Comment by seungwonpark** [comment]
@gshslatexintro/teachers 
@gshslatexintro/graduates-1st-30th 
@gshslatexintro/graduates-31st 
@gshslatexintro/graduates-32nd 
@gshslatexintro/students-33rd 
@gshslatexintro/students-34th 
@gshslatexintro/students-35th 
이 레포지토리를 watch하고 있지 않은 분들이 계셔서 부득이하게 일일이 태그합니다. 관심 부탁드립니다.
https://github.com/gshslatexintro/latex.gs.hs.kr/issues/8

**Comment by simnalamburt** [comment]
simnalamburt@gmail.com 감사합니다!

**Comment by seungwonpark** [comment]
@simnalamburt 초대해드렸습니다. 협회에 대해 관심 가져주셔서 감사합니다.

**Comment by seungwonpark** [comment]
@koosaga 초대해드렸습니다.

**Comment by MariAli-Lover** [comment]
humanbeing1337@gmail.com

**Comment by PhysSong** [comment]
tteu.ingog@gmail.com 초대 부탁드립니다.

**Comment by EC97B0EAB79C** [comment]
@MariAli-Lover @PhysSong 두분 다 초대해드렸습니다.

**Comment by KENNYSOFT** [comment]
525hm@naver.com

**Comment by EC97B0EAB79C** [comment]
@KENNYSOFT 초대해드렸습니다.

**Comment by Qyubey** [comment]
stalemate126@gmail.com 입니다! 잘 부탁드립니다!

**Comment by seungwonpark** [comment]
@Qyubey 초대해드렸습니다.
저는 Owner가 아니라서 댓글 삭제를 못합니다. 삭제를 부탁드립니다.

**Comment by Jungmin2** [comment]
안녕하세요? 저는 35기 이정민입니다.
jungminblog@naver.com

**Comment by EC97B0EAB79C** [comment]
@jungmin2 초대해 드렸습니다
